# Generated by Django 6.0.5 on 2026-05-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(blank=True, max_length=1000)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('life_span', models.CharField(blank=True, max_length=100)),
                ('temperament', models.CharField(blank=True, max_length=1000)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('bred_for', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
