# Generated by Django 6.0.5 on 2026-05-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogbreed',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dogbreed',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
