# Generated by Django 6.0.5 on 2026-05-14 20:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breed', '0002_alter_dogbreed_id_alter_dogbreed_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogbreed',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dogbreed',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dogbreed',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dogbreed',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
