# Generated by Django 6.0.5 on 2026-05-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breed', '0003_alter_dogbreed_height_alter_dogbreed_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogbreed',
            name='life_span',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
