# Generated by Django 6.0.5 on 2026-05-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breed', '0004_alter_dogbreed_life_span'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogbreed',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
