# Generated by Django 6.0.5 on 2026-05-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Breed', '0005_alter_dogbreed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogbreed',
            name='bred_for',
        ),
    ]
